

#ifndef Notification_h
#define Notification_h


#define NOTIFICATION_REFRESH_CATAGOTY @"NOTIFICATION_REFRESH_CATAGOTY"

#define NOTIFICATION_GO_TO_BG @"NOTIFICATION_GO_TO_BG"

#define NOTIFICATION_REFREASH_VOICE_LIST @"NOTIFICATION_REFREASH_VOICE_LIST"

#define NOTIFICATION_NEED_COMPLETE_USERINFO @"NOTIFICATION_NEED_COMPLETE_USERINFO"
#define NOTIFICATION_NEED_LOGIN @"NOTIFICATION_NEED_LOGIN"
#define NOTIFICATION_REFREASH_VOICE_DETAIL @"NOTIFICATION_REFREASH_VOICE_DETAIL"
#define NOTIFICATION_REFREASH_USER_DETAILS @"NOTIFICATION_REFREASH_USER_DETAILS"
#define NOTIFICATION_LOGINSUCESS @"NOTIFICATION_LOGINSUCESS"
#define NOTIFICATION_LOGIOUT @"NOTIFICATION_LOGIOUT"
#define NOTIFICATION_UPDATE_FATELIST @"NOTIFICATION_TAB_CHANGE"
#define NOTIFICATION_PACKAGE_STOPPLAY @"NOTIFICATION_PACKAGE_STOPPLAY"
#define NOTIFICATION_GET_USER_INFO @"NOTIFICATION_GET_USER_INFO"
#define NOTIFICATION_UPDATEUSER_INFO @"NOTIFICATION_UPDATEUSER_INFO"
#define NOTIFICATION_UPDATE_HOME @"NOTIFICATION_UPDATE_HOME"

#define NOTIFICATION_STOP_CURRENT_PLAY @"NOTIFICATION_STOP_CURRENT_PLAY"

#define NOTIFICATION_TABBAR_CENTER_CLICK @"NOTIFICATION_TABBAR_CENTER_CLICK"

#define NOTIFICATION_CHECK_SOCKET_STATE @"NOTIFICATION_CHECK_SOCKET_STATE"


//收到新消息通知
#define NOTIFICATION_SOCKET_MESSAGE_RECEIVED @"NOTIFICATION_SOCKET_MESSAGE_RECEIVED"
//收到用户位置的更新
#define NOTIFICATION_SOCKET_POSITION_RECEIVED @"NOTIFICATION_SOCKET_POSITION_RECEIVED"
//收到用户位置共享
#define NOTIFICATION_SOCKET_POSITION_ONTIME @"NOTIFICATION_SOCKET_POSITION_ONTIME"

//语音消息播放完毕
#define NOTIFICATION_AUDIO_PLAY_FINISHED @"NOTIFICATION_AUDIO_PLAY_FINISHED"
//停止实时共享
#define NOTIFICATION_STOP_REALTIME_SHARE @"NOTIFICATION_STOP_REALTIME_SHARE"


#endif /* Notification_h */


